apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  namespace: qq6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: redis:latest
        resources:
          limits:
            cpu: 0.5
            memory: 500M
          requests:
            cpu: 0.5
            memory: 500M
        ports:
        - containerPort: 6379