apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-deployment
  labels:
    app: realtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
        - name: realtime
          image: redis:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500M"
              cpu: "0.5"
            limits:
              memory: "500M"
              cpu: "0.5"
