apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: realtime
  name: realtime
  namespace: qq6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: realtime
    spec:
      containers:
      - image: redis:latest
        name: redis
        resources:
          limits:
            cpu: 500Mi
            memory: 500m
          requests:
            cpu: 500Mi
            memory: 500m
status: {}