apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpine
  name: alpine
spec:
  containers:
  - image: alpine:edge
    name: alpine
    command: ["sh", "-c", "while true; do echo 'Hello Alpine'; sleep 3; done"]