apiVersion: v1
kind: Service
metadata:
  name: http-service
  namespace: qq8
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: http