# PersistentVolume for MongoDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: qq3
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo  # Adjust this path based on your cluster setup

---

# PersistentVolumeClaim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: qq3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

# ConfigMap for Mongo-Express
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: qq3
data:
  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  ME_CONFIG_BASICAUTH: "false"

---

# Secret for MongoDB and Mongo-Express
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: qq3
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: test
  MONGO_INITDB_ROOT_PASSWORD: test
---

# Service for Mongo StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: qq3
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    name: mongo
  clusterIP: None
  selector:
    app: mongo
---

# StatefulSet for Mongo and Mongo-Express
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-storage
          mountPath: /etc/mongo
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
          name: web
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_MONGODB_URL
        - name: ME_CONFIG_BASICAUTH
        valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_BASICAUTH
       - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
       - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
      volumeMounts:
        - name: mongo-storage
          mountPath: /etc/mongo
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc