# pers volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: qq3
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo  # Adjust this path based on your cluster setup
---
#pv claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: qq3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi