apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: qq3
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
