apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: qq4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80


---
kubectl set image deployment/frontend httpd=httpd:bookworm -n qq4
kubectl rollout status deployment/frontend -n qq4
kubectl get pods -n kube-system | grep etcd

ETCDCTL_API=3 etcdctl snapshot save /snap/etcd-backup.db \
  --endpoints=https://127.0.0.1:2379 \
  --cacert=/etc/kubernetes/pki/etcd/ca.crt \
  --cert=/etc/kubernetes/pki/etcd/server.crt \
  --key=/etc/kubernetes/pki/etcd/server.key


kubectl rollout undo deployment/frontend -n qq4

ETCDCTL_API=3 etcdctl snapshot restore /snap/etcd-backup.db \
  --data-dir /var/lib/etcd


kubectl get deployment frontend -n qq4