apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examinee
  namespace: examinee
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "pods/status", "deployments", "replicationcontrollers"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]