apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examinee
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examinee-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: examinee
subjects:
- kind: ServiceAccount
  name: examinee
  namespace: examinee

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: examinee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      serviceAccountName: examinee
      containers:
      - name: apache
        image: httpd