apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: examinee
  name: examinee
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: examinee
  namespace: examinee
subjects:
  - kind: User
    name: examinee
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: examinee
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examinee-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examinee-cluster-role-binding
subjects:
  - kind: User
    name: examinee
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: examinee-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: examinee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
