apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examinee-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: examinee
roleRef:
  kind: ClusterRole
  name: examinee
  apiGroup: rbac.authorization.k8s.io