apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examinee-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: examinee
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: examinee