apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: examinee
  name: examinee
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "list", "create", "update", "delete"]
