apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
          resources:
            requests:
              cpu: 200m # Request 200m CPU
            limits:
              cpu: 500m # Limit 500m CPU
