apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deployment
  namespace: qq5
  labels:
    dashboard.qq5.org: dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: drupal:10.2.7-php8.2-fpm-bookworm
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    dashboard.qq5.org: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
