apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: drupal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: rupal:10.2.7-php8.2-fpm-bookworm
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: qq5
spec:
  type: LoadBalancer
  ports:
  - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: drupal
  