apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: qq5
spec:
  rules:
  - host: dashboard.qq5.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard
            port:
              number: 80