apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qq2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        team: devops
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
