apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
controlplane $ cat httpd-deployment.yaml  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        volumeMounts:
        - name: shared-storage
          mountPath: /usr/local/apache2/htdocs  
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc