apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.20-bullseye
        volumeMounts:
        - name: shared-storage
          mountPath: /var/lib/postgresql/data 
        env:
        - name: POSTGRES_DB
          value: exampledb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc