apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: qq3
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==         #'root'
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==     #'example'
  ME_CONFIG_MONGODB_ADMINUSERNAME: cm9vdA==    #'root'
  ME_CONFIG_MONGODB_ADMINPASSWORD: ZXhhbXBsZQ== #'example'
