apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: qq3
data:
  ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  ME_CONFIG_BASICAUTH: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: qq3
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
spec:
  selector:
    matchLabels:
      app: mongodb # has to match .spec.template.metadata.labels
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongodb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: mongo-vol
              mountPath: /etc/mongo
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mongo-configmap
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: mongo-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "mongo-sc"
        resources:
          requests:
            storage: 3Gi
