apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mongo
        ports:
        - containerPort: 27017
          name: database
        envFrom:
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: mongo-secret
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 80
          name: mongo-express
        envFrom:
          - secretRef:
              name: mongo-secret