apiVersion: v1
data:
  ME_CONFIG_BASICAUTH: "false"
  ME_CONFIG_MONGODB_URL: mongodb://haziq:haziqpass@mongo:27017/
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mongo-config
  namespace: qq3