apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: qq3
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: dGVzdA== #'test'
  MONGO_INITDB_ROOT_PASSWORD: dGVzdA==
  ME_CONFIG_MONGODB_ADMINUSERNAME: dGVzdA==
  ME_CONFIG_MONGODB_ADMINPASSWORD: dGVzdA==
