apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: qq3
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: qq3
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000
  selector:
    app: mongo